steps:  
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=relayer_SEEDS_GOZ > goz.txt' ]


- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/relayer:$SHORT_SHA'
  - '.'

# Tag the latest version as :latest. We use gcr.io/cloud-builders/docker here
# and not gcr.io/$PROJECT_ID/docker because the latter may not yet exist.
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/relayer:$SHORT_SHA', 'gcr.io/$PROJECT_ID/relayer']
  wait_for: ['Build']
  id: 'latest'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/relayer:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'set'
  - 'image'
  - 'deployment/relayer'
  - 'relayer=gcr.io/$PROJECT_ID/relayer:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
timeout: '1600s'
