steps:  
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=relayer_SEEDS_PYLONSCHAIN > pylons.txt' ]
  
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=relayer_SEEDS_GOZ > goz.txt' ]


- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--build-arg'
  - 'SEEDS_PYLONSCHAIN=$$(cat pylons.txt)'
  - '--build-arg'
  - 'SEEDS_GOZ=$$(cat goz.txt)'
  - '-t'
  - 'gcr.io/$PROJECT_ID/relayer:$SHORT_SHA'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/relayer:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'set'
  - 'image'
  - 'deployment/relayer'
  - 'relayer=gcr.io/$PROJECT_ID/relayer:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
timeout: '1600s'
